sources:
  - mmQTL_GENCODE_expression
  - mmQTL_union_expression
  - mmQTL_union_transcript
  - mmQTL_GENCODE_transcript
  - mmQTL_union_SUPPA_RI
  - mmQTL_GENCODE_SUPPA_RI
  - mmQTL_GENCODE_leafcutter
  - mmQTL_union_leafcutter
  - mmQTL_GENCODE_SUPPA_AF
  - mmQTL_GENCODE_SUPPA_AL
  - mmQTL_union_SUPPA_AF
  - mmQTL_union_SUPPA_AL
  - mmQTL_GENCODE_SUPPA_SE
  - mmQTL_union_SUPPA_SE
  - mmQTL_GENCODE_SUPPA_A3
  - mmQTL_union_SUPPA_A3
  - mmQTL_GENCODE_SUPPA_A5
  - mmQTL_union_SUPPA_A5
targets:
  - mmQTL_GENCODE_expression
  - mmQTL_union_expression
  - mmQTL_union_transcript
  - mmQTL_GENCODE_transcript
  - mmQTL_union_SUPPA_RI
  - mmQTL_GENCODE_SUPPA_RI
  - mmQTL_GENCODE_leafcutter
  - mmQTL_union_leafcutter
  - mmQTL_GENCODE_SUPPA_AF
  - mmQTL_GENCODE_SUPPA_AL
  - mmQTL_union_SUPPA_AF
  - mmQTL_union_SUPPA_AL
  - mmQTL_GENCODE_SUPPA_SE
  - mmQTL_union_SUPPA_SE
  - mmQTL_GENCODE_SUPPA_A3
  - mmQTL_union_SUPPA_A3
  - mmQTL_GENCODE_SUPPA_A5
  - mmQTL_union_SUPPA_A5
threshold: 0.05
outFolder:
    "qvalue_res/"
