import pandas as pd
source_data = config["sources"]
target_data = config["targets"]
outFolder = config["outFolder"]
threshold = str(config["threshold"])

qtl_df = pd.read_excel("/sc/arion/projects/ad-omics/data/references//GWAS/GWAS-QTL_data_dictionary.xlsx", sheet_name = 'QTL')

qtl_check = all(i in qtl_df["dataset"].tolist() for i in source_data + target_data )
 
# write in check for munged sumstats
 
if not all([qtl_check]):
    print(" * QTLs cannot be found in database")
    sys.exit()


rule all:
    input:
        expand( outFolder + "{source}:{target}:{threshold}.qvalue.tsv", source = source_data, target = target_data, threshold = threshold ),
        outFolder + "all_qvalue_merged." + threshold + ".tsv"


rule run_qvalue:
    params:
        source = "{source}",
        target = "{target}",
        script = "scripts/run_qvalue.R"
    output:
        outFolder + "{source}:{target}:{threshold}.qvalue.tsv"
    shell:
        "ml R/3.6.0;"
        "Rscript {params.script} -s {params.source} -t {params.target} -q {threshold} -o {outFolder}"

rule merge_qvalue:
    input:
         expand( outFolder + "{source}:{target}:{threshold}.qvalue.tsv", source = source_data, target = target_data, threshold = threshold )
    params:
        script = "scripts/merge_qvalue.R"
    output:
        outFolder + "all_qvalue_merged." + threshold + ".tsv"
    shell:
        "ml R/3.6.0;"
        "Rscript {params.script} -o {outFolder} -q {threshold}"
