datasets:
 - MiGASti_GFM_Unstim
 - MiGASti_GFM_IFNy
 - MiGASti_GFM_LPS
 - MiGASti_SVZ_Unstim
 - MiGASti_SVZ_IFNy
 - MiGASti_SVZ_LPS
 - Microglia_THA
 - Microglia_SVZ
 - Microglia_MFG
 - Microglia_STG
outFolder: "results/all"
dataCode: "MiGA_MiGASti"
vcf: "/sc/arion/projects/als-omics/microglia_stimulated/Genotype_QC_Pipeline_2.0/output/clean_data/microglia_stimulated_anno.MAF.vcf.gz"
