# MR pipeline
import sys
import pandas as pd
gwas_data = config["gwas"]
qtl_data = config["qtl"]
outFolder = config["outFolder"]
geneMeta = config["geneMeta"]
fdr = config["FDR_option"]

# sanity check - can the GWAS and QTL data be found in the database?
gwas_df = pd.read_excel("/sc/arion/projects/ad-omics/data/references/GWAS/GWAS-QTL_data_dictionary.xlsx", sheet_name = "GWAS")
qtl_df = pd.read_excel("/sc/arion/projects/ad-omics/data/references/GWAS/GWAS-QTL_data_dictionary.xlsx", sheet_name = "QTL")

gwas_check = all(i in gwas_df["dataset"].tolist() for i in gwas_data )
qtl_check = all(i in qtl_df["dataset"].tolist() for i in qtl_data )

if not all([gwas_check, qtl_check]):
    print(" * QTL and/or GWAS cannot be found in database")
    sys.exit()

shell.prefix("export PS1=""; ml anaconda3; CONDA_BASE=$(conda info --base); source $CONDA_BASE/etc/profile.d/conda.sh; ml purge; conda activate snakemake;")

# compute suffix once using the config boolean (parsed from YAML)
suffix = "_MR_wFDR.tsv" if config.get("FDR_option", False) else "_MR.tsv"
merged_suffix = "_wFDR" if config.get("FDR_option", False) else ""

rule all:
    input:
        os.path.join(outFolder, "all_MR_results_merged_H4_0_snp" + merged_suffix + ".tsv.gz"),
        os.path.join(outFolder, "all_MR_results_merged_H4_1_snp" + merged_suffix + ".tsv.gz")

rule run_MR:
    output:
        #  use wildcard placeholders {GWAS} and {QTL}; build full filename string
        os.path.join(outFolder, "{GWAS}", "{QTL}_{GWAS}" + suffix)
    params:
        script = "scripts/run_MR.R",
        fdr = fdr,
        cores = config.get("run_MR_cores", 1),
        plink_bin = config.get("plink_bin", "")
    shell:
        "mkdir -p {outFolder}{wildcards.GWAS};"
        "ml R/4.2.0; ml plink2/2.3;" #ml arrow;"
        "Rscript {params.script} -g {wildcards.GWAS} -q {wildcards.QTL} -f {params.fdr} --cores {params.cores} --plink_bin '{params.plink_bin}' -o {outFolder}{wildcards.GWAS}/ "
   
rule merge_MR_snp_level:
    input:
        expand(os.path.join(outFolder, "{GWAS}", "{QTL}_{GWAS}" + suffix), GWAS = gwas_data, QTL = qtl_data)
    output:
        os.path.join(outFolder, "all_MR_results_merged_H4_0_snp" + merged_suffix + ".tsv.gz"),
        os.path.join(outFolder, "all_MR_results_merged_H4_1_snp" + merged_suffix + ".tsv.gz")
    params:
        script = "scripts/merge_MR_results.R",
        fdr = fdr
    shell:
        "ml R/4.2.0;"
        "Rscript {params.script} -f {params.fdr} --threshold 0 --inFolder {outFolder} --geneMeta {geneMeta};" 
        "Rscript {params.script} -f {params.fdr} --threshold 1 --inFolder {outFolder} --geneMeta {geneMeta}"
