
gwas_data = config["gwas"]
qtl_data = config["qtl"]
outFolder = config["outFolder"]

rule all:
    input:
        outFolder + "all_COLOC_results_merged_H4_0_no_LD.tsv.gz",
        outFolder + "all_COLOC_results_merged_H4_0.5_with_LD.tsv.gz",
        expand( outFolder + "{GWAS}/{QTL}_{GWAS}_COLOC.tsv", GWAS = gwas_data, QTL = qtl_data )
        #outFolder + "all_COLOC_summary_results.tsv.gz"

rule run_COLOC:
    output:
        outFolder + "{GWAS}/{QTL}_{GWAS}_COLOC.tsv",
        outFolder +  "{GWAS}/{QTL}_{GWAS}_COLOC.RData"
    params:
        script = "run_COLOC.R"
    shell:
        "mkdir -p {outFolder}{wildcards.GWAS};"
        "ml R/3.6.0; ml arrow;"
        "Rscript {params.script} -g {wildcards.GWAS} -q {wildcards.QTL} -o {outFolder}{wildcards.GWAS}/ "

rule extract_COLOC_summary:
    input:
        outFolder +  "{GWAS}/{QTL}_{GWAS}_COLOC.RData"
    output:
        outFolder +  "{GWAS}/{QTL}_{GWAS}_COLOC_summary_level.tsv"
    params:
        script = "extract_COLOC_summary.R"
    shell:
        "ml R/3.6.0;"
        "Rscript {params.script} -g {wildcards.GWAS} -q {wildcards.QTL} -i {input} -o {output} "
    
rule merge_COLOC_snp_level:
    input:
        expand( outFolder + "{GWAS}/{QTL}_{GWAS}_COLOC.tsv", GWAS = gwas_data, QTL = qtl_data )
    output:
        outFolder + "all_COLOC_results_merged_H4_0_no_LD.tsv.gz",
        outFolder + "all_COLOC_results_merged_H4_0.5_with_LD.tsv.gz"
    shell:
        "ml R/3.6.0;"
        "Rscript merge_COLOC_results.R --threshold 0 --inFolder {outFolder};" 
        "Rscript merge_COLOC_results.R --threshold 0.5 --ld --inFolder {outFolder} "

rule merge_COLOC_summary_level:
    input:
        expand(outFolder +  "{GWAS}/{QTL}_{GWAS}_COLOC_summary_level.tsv", GWAS = gwas_data, QTL = qtl_data )
    output:
        outFolder + "all_COLOC_summary_results.tsv.gz"
    params:
        script = "merge_COLOC_summary.R"
    shell:
        "ml R/3.6.0;"
        "Rscript {params.script} --inFolder {outFolder}"
